### ISSUE TITLE
Requirements for building under gentoo.

### ISSUE THREAD

**Issue by random25252** [linux-surface/surface-aggregator-module#1]
Hey, I know this is experimental but it is really bothering me that I am not able to get this working!

I am running on a surface book 2:
I have successfully used this module under Ubuntu, fedora, and arch, but I cannot seem to get it to work under Gentoo for some reason. I am able to compile the kernel with your patches, and the CONFIG_SERIAL.. Settings applied, and load it [the module] with insmod, however no battery stats. I know I haven't attached any logs or anything but I don't really know where to start with troubleshooting this, if any logs can help, please let me know and I will send them;

The information I have been able to gather so far from DMESG is that the driver is loaded:
`[   51.871132] surfacegen5_acpi_notify: loading out-of-tree module taints kernel.
[   51.871460] surfacegen5_acpi_notify_san MSHW0091:00: surfacegen5_acpi_notify_san_probe
[   51.871461] surfacegen5_acpi_notify_shps MSHW0153:00: surfacegen5_acpi_notify_shps_probe
[   51.871491] surfacegen5_acpi_notify_shps MSHW0153:00: sg5_base_state_irq_setup
[   51.871509] surfacegen5_acpi_notify_shps MSHW0153:00: failed to get base_presence-int GPIO`

Any help is greatly appreciated.

EDIT: Probably should have mentioned kernel version is 4.18.16

**Comment by qzed** [comment]
I think there may be multiple things going on.

For the main issue: Can you see any `surfacegen5_acpi_notify_ssh_probe` message in the log?

Second: It seems like the base-presence interrupt cannot be set up. This shouldn't affect the battery indicator in any way, as this is just relevant for making sure the indicator is updated when detaching/re-attaching the base. To solve this: Can you check that `CONFIG_GPIOLIB` and `CONFIG_GPIO_ACPI` are set to `y`?

**Comment by random25252** [comment]
GPIOLIB was actually required for me to compile the module, however I had not set , and GPIO_ACPI is also already set to y, so I'm not sure what's going on with that. With the whole batter indicator, I only see san_probe events, and no ssh_probe ones.

**Comment by qzed** [comment]
Okay, I'm not an expert on the kernel config variables, so I'll go into a bit more detail on what I know: The `_ssh` driver is central to the whole module. If that doesn't probe, it won't work. The message that this driver should write to the log is directly at the start of the probing function, so it doesn't get loaded (i.e. there is no error in the probe function itself). Since you have the patches applied and the config variables above set, I don't really have any idea why this is the case. Also it's not related to the kernel version as I'm currently running the same one.

Here's what I know about the required config variables:
- `CONFIG_SERIAL_8250` / `CONFIG_SERIAL_8250_DW` are required for the UART controller
- `CONFIG_GPIOLIB` / `CONFIG_GPIO_ACPI` are required for the base status GPIO-based interrupts (I'm not sure about the first one, and I don't know if there are others required for that)
- `CONFIG_SERIAL_DEV_BUS` / `CONFIG_SERIAL_DEV_CTRL_TTYPORT` are required for the serdev driver subsystem

I'm not sure what else might be required, maybe `CONFIG_SERIAL_8250_DMA` and/or `CONFIG_SERIAL_8250_PCI`?

If you're willing you could have a look at [this](https://github.com/qzed/linux-surfacegen5-acpi-notify/files/2545305/config.txt) config, that's the one I'm currently using.

**Comment by random25252** [comment]
Yeah it's strange because everything you mentioned is already present, I'll compile and see what happens with your config. Thank you for the help
