### ISSUE TITLE
nvidia_uvm must be blacklisted to prevent dGPU from being on at boot

### ISSUE THREAD

**Issue by takintilo** [linux-surface/surface-aggregator-module#54]
There's a kernel module `nvidia_uvm` that `system76-power` doesn't seem to blacklist and is missing from the wiki. On my SB2, if it's not blacklisted, the dGPU will always be on after rebooting and it's impossible to switch to the integrated GPU.

Side note: it seems like it's always impossible to switch back to the integrated GPU after switching to `nvidia`, `compute`, or `hybrid`. For a while I was able to switch back to the iGPU by calling `modprobe -r` on `nvidia_uvm`. However, when I could do this, I had the `nvidia` package installed. I uninstalled it since I already had `nvidia-dkms` installed and seem to have lost this ability. Reinstalling `nvidia` didn't help.

**Comment by qzed** [comment]
Thanks, I'll add it to the wiki.

If you're unable to unload the modules, something is likely using them. You can try to figure out what that is by running `lsof /dev/nvidia0` and `lsof /dev/nvidiactl` (there may be other device files in use blocking unloading). Generally, when you boot with the nvidia drivers not completely blacklisted, the X-server will prevent the driver from being unloaded. As far as I know, that can only be fixed by rebooting with the drivers blacklisted.
